
foo:
  bar: 1




#
# Configure middleware.
#

#middleware:
#  - request_identification
#  - request_tracing
#  - route_metrics




#
# Configure metrics, you can have metrics sent to multiple
# sinks.
#
# See github.com/armon/go-metrics for types of sinks
#

#metrics:
#  - inmem
#  - statsd




#
# Configure your logging, along with hooks.
#

log:
  level: info
#  hooks:
#    syslog:
#      transport: udp
#      server: localhost:514
#      level: debug

